[2024-11-05T20:30:35.192-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_with_custom_email_alerts1.task_filter_biospecimen_analysis manual__2024-11-06T01:24:43.878866+00:00 [queued]>
[2024-11-05T20:30:35.198-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_with_custom_email_alerts1.task_filter_biospecimen_analysis manual__2024-11-06T01:24:43.878866+00:00 [queued]>
[2024-11-05T20:30:35.198-0500] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-11-05T20:30:35.343-0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): task_filter_biospecimen_analysis> on 2024-11-06 01:24:43.878866+00:00
[2024-11-05T20:30:35.347-0500] {standard_task_runner.py:57} INFO - Started process 56407 to run task
[2024-11-05T20:30:35.351-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline_with_custom_email_alerts1', 'task_filter_biospecimen_analysis', 'manual__2024-11-06T01:24:43.878866+00:00', '--job-id', '356', '--raw', '--subdir', 'DAGS_FOLDER/try1.py', '--cfg-path', '/tmp/tmpn3gkw284']
[2024-11-05T20:30:35.352-0500] {standard_task_runner.py:85} INFO - Job 356: Subtask task_filter_biospecimen_analysis
[2024-11-05T20:30:35.478-0500] {task_command.py:416} INFO - Running <TaskInstance: data_pipeline_with_custom_email_alerts1.task_filter_biospecimen_analysis manual__2024-11-06T01:24:43.878866+00:00 [running]> on host mrudula-OMEN-by-HP-Laptop
[2024-11-05T20:30:35.651-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline_with_custom_email_alerts1' AIRFLOW_CTX_TASK_ID='task_filter_biospecimen_analysis' AIRFLOW_CTX_EXECUTION_DATE='2024-11-06T01:24:43.878866+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-06T01:24:43.878866+00:00'
[2024-11-05T20:30:35.659-0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mrudula/airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/mrudula/airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mrudula/airflow/dags/try1.py", line 111, in filter_biospecimen_analysis
    filtered_biospecimen_analysis = biospecimen_analysis[biospecimen_analysis['VALIDATION_FLAG'] == 'Valid']
TypeError: 'NoneType' object is not subscriptable
[2024-11-05T20:30:35.665-0500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=data_pipeline_with_custom_email_alerts1, task_id=task_filter_biospecimen_analysis, execution_date=20241106T012443, start_date=20241106T013035, end_date=20241106T013035
[2024-11-05T20:30:35.835-0500] {standard_task_runner.py:104} ERROR - Failed to execute job 356 for task task_filter_biospecimen_analysis ('NoneType' object is not subscriptable; 56407)
[2024-11-05T20:30:35.843-0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-05T20:30:35.861-0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
